In [9]:
import pandas as pd

df2019 = pd.read_csv("../../data_resources/2019_서울시_상권분석서비스(점포-상권).csv", encoding='cp949')
df2019.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20191,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,11,11,0,0,9,1,0
1,20191,A,골목상권,3110001,이북5도청사,CS100002,중식음식점,1,1,0,0,0,0,0
2,20191,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,3,3,0,0,0,0,0
3,20191,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,2,3,0,0,0,0,1
4,20191,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,1,1,0,0,0,0,0

In [11]:
df2019.columns

Index(['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률',
       '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

In [ ]:
df2019.drop(subset=[])

In [18]:
import pandas as pd

df2020 = pd.read_csv("../../data_resources/2020_서울시_상권분석서비스(점포-상권).csv", encoding='cp949')
df2020.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20201,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,12,12,0,0,0,0,0
1,20201,A,골목상권,3110001,이북5도청사,CS100002,중식음식점,0,0,0,0,0,1,0
2,20201,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,3,3,0,0,0,0,0
3,20201,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,3,4,0,0,0,0,1
4,20201,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,2,2,0,0,0,0,0

In [19]:
import pandas as pd

df2021 = pd.read_csv("../../data_resources/2021_서울시_상권분석서비스(점포-상권).csv", encoding='cp949')
df2021.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20211,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,12,12,0,0,0,0,0
1,20211,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,3,3,0,0,0,0,0
2,20211,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,3,4,0,0,0,0,1
3,20211,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,2,2,0,0,0,0,0
4,20211,A,골목상권,3110001,이북5도청사,CS200001,일반교습학원,4,4,0,0,0,0,0

In [20]:
import pandas as pd

df2022 = pd.read_csv("../../data_resources/2022_서울시_상권분석서비스(점포-상권).csv", encoding='cp949')
df2022.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20221,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,10,10,0,0,0,0,0
1,20221,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,3,3,0,0,0,0,0
2,20221,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,2,3,0,0,0,0,1
3,20221,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,1,1,0,0,0,0,0
4,20221,A,골목상권,3110001,이북5도청사,CS200001,일반교습학원,4,4,0,0,0,0,0

In [21]:
import pandas as pd

df2023 = pd.read_csv("../../data_resources/2023_서울시_상권분석서비스(점포-상권).csv", encoding='cp949')
df2023.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20231,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,10,11,9,1,0,0,1
1,20231,A,골목상권,3110001,이북5도청사,CS100003,일식음식점,1,1,0,0,0,0,0
2,20231,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,3,3,0,0,0,0,0
3,20231,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,2,3,0,0,0,0,1
4,20231,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,1,1,0,0,0,0,0

In [22]:
import pandas as pd

df2024 = pd.read_csv("../../data_resources/2024_서울시 상권분석서비스(점포-상권).csv", encoding='cp949')
df2024.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20241,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,10,11,0,0,0,0,1
1,20241,A,골목상권,3110001,이북5도청사,CS100003,일식음식점,1,1,0,0,0,0,0
2,20241,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,2,2,0,0,50,1,0
3,20241,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,4,5,20,1,0,0,1
4,20241,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,1,1,0,0,0,0,0

In [23]:
dfs = [df2019, df2020, df2021, df2022, df2023, df2024]

for df, year in zip(dfs, range(2019, 2025)):
    df["연도"] = year

merged_df = pd.concat(dfs, ignore_index=True)

merged_df.to_csv("../../data_resources/상권분석_2019_2024_병합.csv", index=False)

print("병합완")

병합완

In [2]:
import pandas as pd
df = pd.read_csv("../../data_resources/상권분석_2019_2024_병합.csv")
df.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,연도
0,20191,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,11,11,0,0,9,1,0,2019
1,20191,A,골목상권,3110001,이북5도청사,CS100002,중식음식점,1,1,0,0,0,0,0,2019
2,20191,A,골목상권,3110001,이북5도청사,CS100008,분식전문점,3,3,0,0,0,0,0,2019
3,20191,A,골목상권,3110001,이북5도청사,CS100009,호프-간이주점,2,3,0,0,0,0,1,2019
4,20191,A,골목상권,3110001,이북5도청사,CS100010,커피-음료,1,1,0,0,0,0,0,2019

In [3]:
df.columns

Index(['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률',
       '폐업_점포_수', '프랜차이즈_점포_수', '연도'],
      dtype='object')

In [4]:
sungsu_df = df[df['상권_코드_명'].isin(["성수2가3동주민센터","성수역 골목형상점가","성수역", "성수동카페거리"])]

In [ ]:
sungsu_df = df[df["상권_코드_명"].str.contains("성수", na=False) ]
#pd.reset_option('display.max_rows', None)
sungsu_df.상권_코드_명.unique()

array(['성수1가1동주민센터', '성수동카페거리', '성수2가3동주민센터', '성수119안전센터', '성수초등학교',
       '성수역', '성수대교남단', '성수역 골목형상점가'], dtype=object)

In [94]:
pd.set_option('display.max_rows', None)
sungsu_df.서비스_업종_코드_명.value_counts()

서비스_업종_코드_명
한식음식점           96
커피-음료           96
사진관             96
건축물청소           96
부동산중개업          96
편의점             96
컴퓨터및주변장치판매      96
가방              96
신발              96
화장품             96
일반의류            96
자동차부품           96
중식음식점           94
일식음식점           92
녹음실             89
패스트푸드점          88
시계및귀금속          86
의약품             85
스포츠클럽           83
가구              80
양식음식점           79
핸드폰             73
가전제품            72
자전거 및 기타운송장비    72
조명용품            72
전자상거래업          72
의료기기            72
운동/경기용품         72
자동차수리           72
스포츠 강습          72
슈퍼마켓            72
제과점             72
문구              72
세탁소             71
분식전문점           70
복권방             67
인테리어            67
재생용품 판매점        65
외국어학원           63
철물점             63
네일숍             62
청과상             61
세무사사무소          61
반찬가게            59
피부관리실           57
화초              57
기타법무서비스         56
일반교습학원          56
미곡판매            53
통번역서비스          53
서적              51
호프-간이주점         49
노래방             49
미용실             49
골프연습장           48
모터사이클수리         48
예술학원            48
주유소             48
치과의원            48
일반의원            48
가전제품수리          48
섬유제품            48
유아의류            48
예술품             48
주류도매            48
여행사             46
자동차미용           45
미용재료            44
가정용품임대          44
전자게임장           42
여관              41
당구장             41
안경              35
수산물판매           35
애완동물            34
회계사사무소          30
변호사사무소          29
모터사이클및부품        29
치킨전문점           27
독서실             27
기타오락장           27
악기              25
고시원             24
의류임대            24
볼링장             24
한의원             24
변리사사무소          24
법무사사무소          24
PC방             24
육류판매            24
컴퓨터학원           23
완구              23
중고차판매           17
비디오/서적임대         8
중고가구             7
동물병원             4
통신기기수리           3
Name: count, dtype: int64

In [ ]:
print(garosugil_df.서비스_업종_코드_명.value_counts())
pd.reset_option('display.max_rows', None)

서비스_업종_코드_명
한식음식점           24
중식음식점           24
일식음식점           24
양식음식점           24
제과점             24
패스트푸드점          24
치킨전문점           24
분식전문점           24
호프-간이주점         24
커피-음료           24
일반교습학원          24
예술학원            24
컴퓨터학원           24
스포츠 강습          24
일반의원            24
치과의원            24
한의원             24
동물병원            24
변호사사무소          24
변리사사무소          24
법무사사무소          24
회계사사무소          24
세무사사무소          24
당구장             24
기타오락장           24
복권방             24
스포츠클럽           24
악기              24
자동차수리           24
미용실             24
네일숍             24
피부관리실           24
세탁소             24
가전제품수리          24
부동산중개업          24
여관              24
게스트하우스          24
노래방             24
독서실             24
녹음실             24
사진관             24
통번역서비스          24
건축물청소           24
여행사             24
의류임대            24
슈퍼마켓            24
편의점             24
핸드폰             24
컴퓨터및주변장치판매      24
주류도매            24
미곡판매            24
유아의류            24
육류판매            24
반찬가게            24
일반의류            24
가방              24
신발              24
안경              24
시계및귀금속          24
재생용품 판매점        24
의약품             24
의료기기            24
서적              24
문구              24
화장품             24
미용재료            24
운동/경기용품         24
자전거 및 기타운송장비    24
완구              24
섬유제품            24
화초              24
애완동물            24
가구              24
가전제품            24
철물점             24
전자상거래업          24
인테리어            24
조명용품            24
자동차부품           24
예술품             24
외국어학원           23
골프연습장           22
가정용품임대           9
기타법무서비스          8
중고차판매            7
청과상              7
고시원              7
비디오/서적임대         5
PC방              4
통신기기수리           2
모터사이클수리          1
Name: count, dtype: int64

In [70]:
garosugil_df = df[df["상권_코드_명"].str.contains("가로수길", na=False) ]
garosugil_df.상권_코드_명.unique()

array(['가로수길'], dtype=object)

### 연도별 점포수 비교

In [72]:
sungsu_df[['연도', "점포_수"]].groupby(by="연도").sum()

      점포_수
연도
2019  6909
2020  7442
2021  7846
2022  8414
2023  8813
2024  9024

In [73]:
garosugil_df[['연도', "점포_수"]].groupby(by="연도").sum()

      점포_수
연도
2019  5338
2020  5442
2021  5507
2022  5769
2023  6193
2024  6218

## 연도별 프랜차이즈점포수

In [74]:
sungsu_df[['연도', "프랜차이즈_점포_수"]].groupby(by="연도").sum()

      프랜차이즈_점포_수
연도
2019         576
2020         614
2021         655
2022         691
2023         682
2024         659

In [75]:
garosugil_df[['연도', "프랜차이즈_점포_수"]].groupby(by="연도").sum()

      프랜차이즈_점포_수
연도
2019         481
2020         476
2021         474
2022         458
2023         457
2024         454

### 개업수 비교

In [76]:
sungsu_df[['연도', "개업_점포_수"]].groupby(by="연도").sum()

      개업_점포_수
연도
2019      375
2020      304
2021      292
2022      349
2023      336
2024      268

In [77]:
garosugil_df[['연도', "개업_점포_수"]].groupby(by="연도").sum()

      개업_점포_수
연도
2019      265
2020      185
2021      202
2022      211
2023      287
2024      161

In [78]:
sungsu_df[['연도', "개업_율"]].groupby(by="연도").sum()

      개업_율
연도
2019  4480
2020  2826
2021  3035
2022  3181
2023  3271
2024  2390

In [79]:
garosugil_df[['연도', "개업_율"]].groupby(by="연도").sum()

      개업_율
연도
2019  1598
2020   739
2021   966
2022  1046
2023  1573
2024   571

### 폐업점포수

In [80]:
sungsu_df[['연도', "폐업_점포_수"]].groupby(by="연도").sum()

      폐업_점포_수
연도
2019      186
2020      184
2021      181
2022      213
2023      240
2024      268

In [81]:
garosugil_df[['연도', "폐업_점포_수"]].groupby(by="연도").sum()

      폐업_점포_수
연도
2019      215
2020      192
2021      159
2022      152
2023      186
2024      186

In [82]:
sungsu_df[['연도', '폐업_률']].groupby(by="연도").sum()

      폐업_률
연도
2019  1982
2020  1544
2021  1894
2022  1946
2023  2207
2024  2346

In [83]:
garosugil_df[['연도', '폐업_률']].groupby(by="연도").sum()

      폐업_률
연도
2019  1081
2020   997
2021   689
2022   747
2023  1006
2024   997